// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegnalHome.Server;

#nullable disable

namespace RegnalHome.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230807173000_second")]
    partial class second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RegnalHome.Common.Models.IrrigationModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IrrigationLengthMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("IrrigationTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastCommunication")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IrrigationModules");
                });

            modelBuilder.Entity("RegnalHome.Common.Models.Log", b =>
                {
                    b.Property<int>("Component")
                        .HasColumnType("int");

                    b.Property<int>("LogLevel")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Component");

                    b.ToTable("Log");
                });
#pragma warning restore 612, 618
        }
    }
}
